export const BLOGS = [
    {
        title: "2025 Trends in Business Sales & Funding Landscape",
        desc: "Explore the latest trends shaping business sales and funding opportunities in 2025.",
        image: "/images/blog1.svg",
        category: "Business Trends",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "December 12, 2024",
    },
    {
        title: "Sell-Side Advisory: What It Is & Why You Might Need It",
        desc: "Understanding the role of sell-side advisory in maximizing business value during sales.",
        image: "/images/blog2.svg",
        category: "Business Advisory",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "November 28, 2024",
    },
    {
        title: "Understanding Business Credit Cards & Lines of Credit",
        desc: "A comprehensive guide to business credit options and how to secure them.",
        image: "/images/blog3.svg",
        category: "Business Funding",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "November 14, 2024",
    },
    {
        title: "Affiliate Referral Programs: How CPAs and Attorneys Can Add Value",
        desc: "Learn how professionals can benefit from affiliate referral programs in business consulting.",
        image: "/images/blog1.svg",
        category: "Partnerships",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "October 31, 2024",
    },
    {
        title: "Success Stories: How We Structured a Deal That Increased Seller Take...",
        desc: "Real case study of how strategic deal structuring maximized seller returns.",
        image: "/images/blog2.svg",
        category: "Case Studies",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "October 17, 2024",
    },
    {
        title: "Preparing the Financial Documentation Buyers Want to See",
        desc: "Essential financial documents and preparation strategies for business sales.",
        image: "/images/blog3.svg",
        category: "Business Sales",
        author: "Phillip Crawford",
        authorRole: "Founder",
        authorCompany: "PAC Consulting",
        authorCompanyUrl: "#",
        authorImage: "/images/testimonials/person1.jpg",
        date: "October 3, 2024",
    },
];
