export const TESTIMONIALS = [
    {
        name: "Anthony Avery",
        role: "Business Owner",
        company: "Small Business",
        companyUrl: "#",
        image: "/images/testimonials/person1.jpg",
        content: "Very prompt and responsive with any questions I had. Explained the process simply and efficiently. Got what I came here for and received a $65k business credit card limit on the first try. Thank you",
        time: "3:45 PM",
        date: "Jun 20, 2024",
    },
    {
        name: "The Grind",
        role: "Entrepreneur",
        company: "Startup",
        companyUrl: "#",
        image: "/images/testimonials/person2.jpg",
        content: "Phil is the man with a Plan! I was in a horrible position credit wise and truthfully just in life in general but after our first consultation my level of optimism went through the roof. He is very knowledgeable at what he does and is a man of his word all he asks of you is to be patient. So that's exactly what I did, trusted the process and just after the first phase I've seen a major change in my credit. I highly recommend him and his team if you are looking to join a group of Wealth minded individuals that are driven by the success of those they work with.",
        time: "11:10 AM",
        date: "Jul 2, 2024",
    },
    {
        name: "Sam Saleh",
        role: "Business Owner",
        company: "Enterprise",
        companyUrl: "#",
        image: "/images/testimonials/person3.jpg",
        content: "I've had a great experience working with PAC Consulting and Phill. The team is knowledgeable, responsive, and truly committed to helping their clients succeed. Phill, in particular, goes above and beyond to provide valuable insights and practical guidance throughout the process. Their professionalism and attention to detail really stand out, and I would gladly recommend them to anyone looking for reliable and results-driven business support.",
        time: "9:30 AM",
        date: "Aug 15, 2023",
    },
    {
        name: "Joie Van Zandt",
        role: "Startup Founder",
        company: "Tech Startup",
        companyUrl: "#",
        image: "/images/testimonials/person4.jpg",
        content: "I can't express the depth of my appreciation for Phillip. He swooped in and saved a business deal for me when I was backed into a corner. He stayed with me all the way, was professional, patient, and so confident which I needed badly because I was within an inch from losing my start-up business when he came in changed the playing field for me and my business. He has my respect and my vote for the #1 person.",
        time: "2:00 PM",
        date: "Sep 5, 2024",
    },
];
