create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
